apiVersion: v1
kind: Service
metadata:
 name: sre-demo
spec:
 type: {{ .Values.service.type }}
 selector:
  app: sre-demo
 ports:
 - name: http
   port: {{ .Values.service.port }}
   targetPort: {{ .Values.service.targetPort }}
 - name: metrics
   port: {{ .Values.service.metricsPort }}
   targetPort: {{ .Values.service.metricsPort }}