apiVersion: v1
kind: Service
metadata:
  name: sre-demo
spec:
  selector:
    app: sre-demo
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 9090
